# Generated by Django 3.2.7 on 2021-12-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20211203_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AddField(
            model_name='post',
            name='board_name',
            field=models.CharField(default='Jobs', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='post',
            table='board',
        ),
    ]
