# Generated by Django 3.2.7 on 2021-12-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_auto_20211218_1215'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
