# Generated by Django 3.2.7 on 2021-12-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
    ]
