# Generated by Django 3.2.7 on 2021-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_auto_20211218_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board_name',
            field=models.CharField(default='Posts', max_length=32),
        ),
    ]
