version: "3.7"
services:
  nginx:
    image: nginx
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_test_image:4
    networks:
      - network
    volumes:
      - static-volume:/home/radhelper/staticfiles
      - media-volume:/home/radhelper/media
    secrets:
      - MARIADB_PASSWORD
      - DJANGO_SECRET_KEY
  mariadb:
    image: mariadb:10.6
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_USER: django
      MARIADB_DATABASE: django
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true