# Generated by Django 3.2.7 on 2021-12-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
