# Generated by Django 3.2.7 on 2021-12-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
