# Generated by Django 3.2.7 on 2021-12-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_radiologist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Radiologist',
        ),
    ]
