# Generated by Django 3.2.7 on 2021-12-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='radiologist',
            field=models.BooleanField(default=False),
        ),
    ]
