# Generated by Django 3.2.7 on 2021-12-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profile_radiologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='radiologist',
        ),
    ]
