# Generated by Django 3.2.7 on 2021-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_profile_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaultimage.png', upload_to='profile/'),
        ),
    ]
