# Generated by Django 3.2.7 on 2022-05-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
    ]
