# Generated by Django 3.2.7 on 2021-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagecommentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storagecomment/'),
        ),
    ]
