# Generated by Django 3.2.7 on 2021-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagecommentapp', '0002_storagecomment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagecomment',
            name='image',
        ),
        migrations.AddField(
            model_name='storagecomment',
            name='upload',
            field=models.FileField(blank=True, upload_to='storagecomment/'),
        ),
    ]
