# Generated by Django 3.2.7 on 2021-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0002_auto_20211118_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='upload',
            field=models.FileField(blank=True, upload_to='storage/%Y/%m/%d'),
        ),
    ]
