# Generated by Django 3.2.7 on 2022-02-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_auto_20220127_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='attached',
        ),
        migrations.AddField(
            model_name='storage',
            name='upload',
            field=models.FileField(blank=True, upload_to='storage/%Y/%m/%d'),
        ),
    ]
