# Generated by Django 3.2.7 on 2021-11-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_remove_comment_modify_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='storage',
        ),
    ]
