# Generated by Django 3.2.7 on 2022-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcommentapp', '0003_postcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postcomment/%Y/%m/%d'),
        ),
    ]
