# Generated by Django 3.2.7 on 2021-10-15 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0008_auto_20211016_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='article/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
