# Generated by Django 3.2.7 on 2021-11-15 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0013_auto_20211029_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='article/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='article/'),
            preserve_default=False,
        ),
    ]
