# Generated by Django 3.2.7 on 2021-12-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0017_rename_specialty_article_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article/%Y/%m/%d'),
        ),
    ]
